Vertical format implemented (?)
ace-lab/pl-ucb-faded-parsons pull request #10
Opened 2022-09-19 08:03 UTC by nelson-lojo

I made some changes to allow instructors to specify whether or not to render the boxes in a Faded Parsons Problem stacked vertically or side-by-side (as before).

I will modify `pl-faded-parsons.md` in a future commit to fully describe this behavior. I opened this pull request now to make sure that the approach is sensible.

2022-09-19 17:59 UTC, SybelBlue requested changes
Looks like a great improvement. Thanks for doing this Nelson! 

You may disregard the commentary I left at your discretion, just resubmit when you're ready and I'll approve.

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            #   of 16 Aug 2022
Is there no way to wrap this code in a `<pl-code>` block instead?

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            formatter = pygments.formatters.HtmlFormatter(**formatter_opts)
Recommend combining into
``` python
formatter = pygments.formatters.HtmlFormatter(
    style='friendly', 
    cssclass='mb-2 rounded', 
    prestyles='padding: 0.5rem; margin-bottom: 0px;', 
    noclasses=True
)
```
That way if the kwargs ever change and they silently update their pl-code implementation we have a hope of getting a static warning.

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +        def get_child_contents_bytag(element, tag: str) -> str:
Recommend `get_child_text_by_tag` for clarity

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            #   of 16 Aug 2022
You are doing a render call to `pl-faded-parsons-question` at the end of the method, maybe you can do a render call to `pl-code` here...

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons-question.mustache
> +    part of the `vertical` dictionary passed to the rendering method }}
I think it would be helpful to write a line here explaining why it is important that they do not dereference.

2022-09-19 17:59 UTC, SybelBlue commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            return match.text
Can be condensed via comprehension:
``` python
return next((child.text for child in element if child.tag == tag), "")
```

2022-09-26 01:20 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            return match.text
changed

2022-09-26 01:21 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons-question.mustache
> +    part of the `vertical` dictionary passed to the rendering method }}
I decided to duplicate the `answers_name` data inside that frame and quickly describe how our mustache engine determines what data is in scope

2022-09-26 01:21 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +        def get_child_contents_bytag(element, tag: str) -> str:
changed

2022-09-26 01:22 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            formatter = pygments.formatters.HtmlFormatter(**formatter_opts)
That makes sense. Changed

2022-09-26 01:23 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons.py
> +            #   of 16 Aug 2022
The PL docs don't seem to describe this, but there might be a hack where we look for the file in `<pl-root>/elements/pl-code` and import it.

Is that any better than keeping the somewhat duplicated code?

2022-09-26 01:28 UTC, nelson-lojo commented
I added a little bit to `pl-faded-parsons.md` to lightly describe how to use `format="vertical"`. If there's any clarifications needed, please let me know.

2022-09-26 01:30 UTC, nelson-lojo commented on elements/pl-faded-parsons/pl-faded-parsons.js
> +      'solution_label' : "",
I removed this label because it was rendered between the pre-text and post-text, so it would break the continuity of the code as presented to the student.

2022-09-26 18:32 UTC, SybelBlue approved these changes
Looking great!

2022-09-26 23:49 UTC, merged